### **1. Abrir la base**

In [2]:
import pandas as pd
import altair as alt

# Cargar archivo CSV
lolla = pd.read_csv(r"/content/Base de datos Lollapalooza 1(Base de datos 1) (1).csv", delimiter=",", encoding="utf-8", dtype= {"edicion": int})
lolla.head()

,edicion lolla,artista,genero musical 01,genero musical 02,genero musical 03,integrantes,nacionalidad,headliner,escenario,veces en lollapalooza
0,2011,The Killers,Rock alternativo,Post-punk revival,New wave,4.0,Estadounidense,Sí,Coca Cola Zero Stage,1.0
1,2011,Jane's Addiction,Rock,Hard Rock,Punk Rock,4.0,Estadounidense,Sí,Claro Stage,1.0
2,2011,Kanye West,Hip Hop,Rap,Pop,1.0,Estadounidense,Sí,Coca Cola Zero Stage,1.0
3,2011,Cypress Hill,Rap,Hip Hop,Rap Rock,4.0,Estadounidense,No,Claro Stage,1.0
4,2011,30 Secons To Mars,Rock,Rock alternativo,Metal progresivo,4.0,Estadounidense,No,Coca Cola Zero Stage,1.0

### **2. Tamaño y estructura de la base**

In [3]:
lolla.shape

(1053, 10)

In [4]:
lolla.columns

Index(['edicion lolla ', 'artista ', 'genero musical 01', 'genero musical 02',
       'genero musical 03', 'integrantes', 'nacionalidad', 'headliner',
       'escenario', 'veces en lollapalooza'],
      dtype='object')

In [5]:
lolla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1053 entries, 0 to 1052
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   edicion lolla          1053 non-null   int64
 1   artista                1053 non-null   object
 2   genero musical 01      1051 non-null   object
 3   genero musical 02      959 non-null    object
 4   genero musical 03      697 non-null    object
 5   integrantes            1040 non-null   float64
 6   nacionalidad           1053 non-null   object
 7   headliner              1053 non-null   object
 8   escenario              1053 non-null   object
 9   veces en lollapalooza  1052 non-null   float64
dtypes: float64(2), int64(1), object(7)
memory usage: 82.4+ KB

### **3. Columnas individuales**

In [6]:
lolla["edicion lolla "].head()

0    2011
1    2011
2    2011
3    2011
4    2011
Name: edicion lolla , dtype: int64

In [7]:
lolla["genero musical 01"].head()

0    Rock alternativo
1                Rock
2             Hip Hop
3                Rap
4                Rock
Name: genero musical 01, dtype: object

In [8]:
lolla["genero musical 02"].head()

0    Post-punk revival
1            Hard Rock
2                  Rap
3              Hip Hop
4     Rock alternativo
Name: genero musical 02, dtype: object

In [9]:
lolla["genero musical 03"].head()

0            New wave
1           Punk Rock
2                 Pop
3            Rap Rock
4    Metal progresivo
Name: genero musical 03, dtype: object

### **4. Contar categorías**

In [10]:
lolla["edicion lolla "].value_counts()

edicion lolla
2019    125
2018    100
2022     93
2024     91
2023     90
2026     90
2025     74
2015     65
2017     61
2014     59
2016     57
2013     54
2011     50
2012     44
Name: count, dtype: int64

In [11]:
lolla["genero musical 01"].value_counts()

genero musical 01
Electrónica         95
Rock alternativo    73
Pop                 72
Rock                65
Hip hop             44
                    ..
Hyperpop             1
Trap Latino          1
Hardcore             1
Pop melancólico      1
Synth-pop            1
Name: count, Length: 204, dtype: int64

In [12]:
lolla["genero musical 02"].value_counts()

genero musical 02
Electrónica         44
Pop                 41
Indie pop           40
R&B                 32
Rock alternativo    30
                    ..
Cumbia pop           1
Pachanga             1
Dreampop             1
Pop                  1
Música andina        1
Name: count, Length: 227, dtype: int64

In [13]:
lolla["genero musical 03"].value_counts()

genero musical 03
Electrónica          27
Rock alternativo     24
R&B                  23
Indie pop            21
House                19
                     ..
Indie                 1
Drum and Bass         1
Rumba                 1
Cumbias               1
Música folclórica     1
Name: count, Length: 195, dtype: int64

### **5. Ordenar datos**

In [14]:
lolla_generos = lolla.melt(
    id_vars=["edicion lolla "],
    value_vars=["genero musical 01", "genero musical 02", "genero musical 03"],
    value_name="genero"
).dropna()

lolla_generos

      edicion lolla            variable             genero
0               2011  genero musical 01   Rock alternativo
1               2011  genero musical 01               Rock
2               2011  genero musical 01            Hip Hop
3               2011  genero musical 01               Rap
4               2011  genero musical 01               Rock
...              ...                ...                ...
3152            2026  genero musical 03               Rock
3154            2026  genero musical 03            Hip hop
3156            2026  genero musical 03          Post-punk
3157            2026  genero musical 03            Cumbias
3158            2026  genero musical 03  Música folclórica

[2707 rows x 3 columns]

In [15]:
lolla_generos = lolla_generos.drop(columns=["variable"])
lolla_generos

      edicion lolla              genero
0               2011   Rock alternativo
1               2011               Rock
2               2011            Hip Hop
3               2011               Rap
4               2011               Rock
...              ...                ...
3152            2026               Rock
3154            2026            Hip hop
3156            2026          Post-punk
3157            2026            Cumbias
3158            2026  Música folclórica

[2707 rows x 2 columns]

In [16]:
tabla_generos = lolla_generos.groupby(["edicion lolla ", "genero"]).size(). reset_index(name="cantidad")
tabla_generos

      edicion lolla         genero  cantidad
0               2011   Alternativo         2
1               2011         Blues         1
2               2011    Blues Rock         1
3               2011       Britpop         1
4               2011   Chamber pop         1
...              ...           ...       ...
1164            2026         Trap          1
1165            2026   Trap Latino         1
1166            2026  Tribal house         1
1167            2026         Trova         1
1168            2026        Urbano         3

[1169 rows x 3 columns]

In [17]:
top_generos = tabla_generos.groupby("genero")["cantidad"].sum().nlargest(10).index
tabla_top = tabla_generos[tabla_generos["genero"].isin(top_generos)]
tabla_top

      edicion lolla             genero  cantidad
14              2011       Electrónica         9
28              2011           Hip hop         2
35              2011         Indie pop         1
42              2011               Pop         2
44              2011          Pop rock         2
...              ...               ...       ...
1116            2026               Pop        10
1126            2026          Pop rock         6
1138            2026               R&B         5
1147            2026              Rock         5
1149            2026  Rock alternativo        15

[130 rows x 3 columns]

### 6. **Gráfico con Altair**

In [18]:
grafico = alt.Chart(tabla_top).mark_bar().encode(
    x="edicion lolla :O",
    y="cantidad:Q",
    color="genero:N",
    tooltip=["edicion lolla ", "genero", "cantidad"]
).properties(
    title="Diversificación de géneros musicales por edición"
)

grafico

alt.Chart(...)

In [19]:
lolla_headliners = lolla[lolla["headliner"] == "Sí"]
lolla_headliners

,edicion lolla,artista,genero musical 01,genero musical 02,genero musical 03,integrantes,nacionalidad,headliner,escenario,veces en lollapalooza
0,2011,The Killers,Rock alternativo,Post-punk revival,New wave,4.0,Estadounidense,Sí,Coca Cola Zero Stage,1.0
1,2011,Jane's Addiction,Rock,Hard Rock,Punk Rock,4.0,Estadounidense,Sí,Claro Stage,1.0
2,2011,Kanye West,Hip Hop,Rap,Pop,1.0,Estadounidense,Sí,Coca Cola Zero Stage,1.0
50,2012,Björk,Electrónica,Art Pop,Experimental,1.0,Islandesa,Sí,Claro-LG Stage,1.0
55,2012,Foo Fighters,Rock,Hard Rock,Grunge,7.0,Estadounidense,Sí,Claro-LG Stage,1.0
...,...,...,...,...,...,...,...,...,...,...
977,2026,Chappel Roan,Synth pop,Pop,Pop indie,1.0,Estadounidense,Sí,Cenco Malls Stage,1.0
982,2026,Deftones,Metal alternativo,Nu metal,Rock alternativo,4.0,Estadounidense,Sí,Banco de Chile Stage,2.0
988,2026,Lorde,Art pop,Synth pop,Dream pop,1.0,Neozelandesa-Croata,Sí,Banco de Chile Stage,2.0
989,2026,Los Bunkers,Rock alternativo,Pop rock,NaN,5.0,Chilena,Sí,Banco de Chile Stage,2.0
994,2026,Skrillex,Electrónica,Dubstep,Dance,1.0,Estadounidense,Sí,Banco de Chile Stage,3.0

In [20]:
headliners_generos = lolla_headliners.melt(
    id_vars=["edicion lolla "],
    value_vars=["genero musical 01", "genero musical 02", "genero musical 03"],
    value_name="genero"
).dropna()

headliners_generos = headliners_generos.drop(columns=["variable"])
headliners_generos

     edicion lolla             genero
0              2011  Rock alternativo
1              2011              Rock
2              2011           Hip Hop
3              2012       Electrónica
4              2012             Rock
..              ...               ...
228            2026          Pop soul
229            2026         Pop indie
230            2026  Rock alternativo
231            2026         Dream pop
233            2026             Dance

[221 rows x 2 columns]

In [21]:
tabla_headliners = headliners_generos.groupby(["edicion lolla ", "genero"]).size().reset_index(name="cantidad")
tabla_headliners

     edicion lolla              genero  cantidad
0              2011          Hard Rock         1
1              2011            Hip Hop         1
2              2011           New wave         1
3              2011                Pop         1
4              2011  Post-punk revival         1
..              ...                ...       ...
178            2026           Pop soul         1
179            2026                R&B         3
180            2026    Rap alternativo         1
181            2026   Rock alternativo         3
182            2026          Synth pop         2

[183 rows x 3 columns]

In [22]:
tabla_headliners_flourish = tabla_headliners[["edicion lolla ", "genero", "cantidad"]]
tabla_headliners_flourish.to_csv("tabla_headliners.csv", index=False)

from google.colab import files
files.download("tabla_headliners.csv")

In [23]:
tabla_headliners_flourish = tabla_headliners[["genero", "edicion lolla ", "cantidad"]]
tabla_headliners_flourish.to_csv("tabla_headliners.csv", index=False)

from google.colab import files
files.download("tabla_headliners.csv")

In [24]:
tabla_headliners_flourish = tabla_headliners[["edicion lolla ", "genero", "cantidad"]].copy()
tabla_headliners_flourish.columns = ["grupo", "nombre", "valor"]
tabla_headliners_flourish.to_csv("tabla_headliners2.csv", index=False)

from google.colab import files
files.download("tabla_headliners2.csv")

In [25]:
tabla_headliners_flourish = tabla_headliners[["genero", "edicion lolla ", "cantidad"]].copy()
tabla_headliners_flourish.columns = ["nombre", "grupo", "valor"]
tabla_headliners_flourish.to_csv("tabla_headliners2.csv", index=False)

from google.colab import files
files.download("tabla_headliners2.csv")

In [26]:
lolla_generos_limpio = lolla_generos.dropna(subset=["genero"])
lolla_generos_limpio

      edicion lolla              genero
0               2011   Rock alternativo
1               2011               Rock
2               2011            Hip Hop
3               2011               Rap
4               2011               Rock
...              ...                ...
3152            2026               Rock
3154            2026            Hip hop
3156            2026          Post-punk
3157            2026            Cumbias
3158            2026  Música folclórica

[2707 rows x 2 columns]

In [27]:
top15_generos = lolla_generos_limpio.groupby("genero")["genero"].count().nlargest(15).index
tabla_top15 = lolla_generos_limpio[lolla_generos_limpio["genero"].isin(top15_generos)]
tabla_top15 = tabla_top15.groupby(["edicion lolla ", "genero"]).size().reset_index(name="cantidad")
tabla_top15

     edicion lolla             genero  cantidad
0              2011             Dance         3
1              2011       Electrónica         9
2              2011           Hip hop         2
3              2011         Indie pop         1
4              2011               Pop         2
..              ...               ...       ...
177            2026          Reguetón        10
178            2026              Rock         5
179            2026  Rock alternativo        15
180            2026              Soul         2
181            2026              Trap         5

[182 rows x 3 columns]

In [28]:
grafico_norm = alt.Chart(tabla_top15).mark_bar().encode(
    y="edicion lolla :O",
    x=alt.X("cantidad:Q", stack="normalize", axis=alt.Axis(format="%")),
    color="genero:N",
    tooltip=["edicion lolla ", "genero", "cantidad"]
).properties(
    title="Diversificación relativa de géneros musicales por edición"
)

grafico_norm

alt.Chart(...)

In [29]:
total_bandas = lolla.groupby("edicion lolla ").size().reset_index(name="total_bandas")
total_bandas

    edicion lolla   total_bandas
0             2011            50
1             2012            44
2             2013            54
3             2014            59
4             2015            65
5             2016            57
6             2017            61
7             2018           100
8             2019           125
9             2022            93
10            2023            90
11            2024            91
12            2025            74
13            2026            90

In [30]:
total_generos = lolla_generos_limpio.groupby("edicion lolla ")["genero"].nunique().reset_index(name="total_generos")
total_generos

    edicion lolla   total_generos
0             2011             71
1             2012             66
2             2013             81
3             2014             71
4             2015             63
5             2016             76
6             2017             71
7             2018            102
8             2019            113
9             2022             68
10            2023             73
11            2024            103
12            2025             94
13            2026            117

In [31]:
tabla_combinada = total_bandas.merge(total_generos, on="edicion lolla ")
tabla_combinada

    edicion lolla   total_bandas  total_generos
0             2011            50             71
1             2012            44             66
2             2013            54             81
3             2014            59             71
4             2015            65             63
5             2016            57             76
6             2017            61             71
7             2018           100            102
8             2019           125            113
9             2022            93             68
10            2023            90             73
11            2024            91            103
12            2025            74             94
13            2026            90            117

In [32]:
barras = alt.Chart(tabla_combinada).mark_bar(color="steelblue", opacity=0.7).encode(
    x="edicion lolla :O",
    y=alt.Y("total_bandas:Q", title="Total de bandas"),
    tooltip=["edicion lolla ", "total_bandas", "total_generos"]
)

linea = alt.Chart(tabla_combinada).mark_line(color="red", point=True).encode(
    x="edicion lolla :O",
    y=alt.Y("total_generos:Q", title="Total de géneros únicos"),
    tooltip=["edicion lolla ", "total_generos"]
)

grafico_combinado = (barras + linea).properties(
    title="Crecimiento de bandas y diversidad de géneros por edición"
).resolve_scale(y="independent")

grafico_combinado

alt.LayerChart(...)

In [33]:
!pip install vl-convert-python

Collecting vl-convert-python
  Downloading vl_convert_python-1.9.0.post1-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.1 kB)
Downloading vl_convert_python-1.9.0.post1-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (33.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 42.2 MB/s eta 0:00:00
Installing collected packages: vl-convert-python
Successfully installed vl-convert-python-1.9.0.post1

In [34]:
grafico_norm.save("vis_01.png", scale_factor=3.0)
grafico_combinado.save("vis_02.png", scale_factor=3.0)

In [35]:
from PIL import Image
from google.colab import files

img1 = Image.open("vis_01.png")
img1.convert("RGB").save("vis_01.jpg")
files.download("vis_01.jpg")

img2 = Image.open("vis_02.png")
img2.convert("RGB").save("vis_02.jpg")
files.download("vis_02.jpg")

In [36]:
grafico_norm.save("vis_01.png", scale_factor=3.0)
grafico_combinado.save("vis_02.png", scale_factor=3.0)

In [37]:
from PIL import Image
from google.colab import files

img1 = Image.open("vis_01.png")
img1.convert("RGB").save("vis_01.jpg")
files.download("vis_01.jpg")

img2 = Image.open("vis_02.png")
img2.convert("RGB").save("vis_02.jpg")
files.download("vis_02.jpg")

In [38]:
import unicodedata

def normaliza(s):
    s = s.lower().strip()
    s = ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')
    return s

def categoria(g):
    n = normaliza(g)
    if 'rock' in n or 'punk' in n or 'grunge' in n or 'metal' in n or 'emo' in n:
        return 'Rock'
    if 'pop' in n and 'hip' not in n:
        return 'Pop'
    if 'electro' in n or 'house' in n or 'techno' in n or 'tecno' in n or 'trance' in n or 'dance' in n or 'rave' in n or 'dubstep' in n or 'drum' in n or 'jungle' in n or 'breakbeat' in n or 'bass' in n:
        return 'Electrónica'
    if 'hip hop' in n or 'rap' in n or 'trap' in n or 'drill' in n:
        return 'Hip Hop / Rap'
    if 'reggaeton' in n or 'regueton' in n or 'reggueton' in n or 'urbano' in n or 'urbana' in n or 'rkt' in n or 'dembow' in n:
        return 'Urbano / Reguetón'
    if 'r&b' in n or 'soul' in n:
        return 'R&B / Soul'
    if 'reggae' in n or 'ska' in n or 'dub' in n:
        return 'Reggae / Ska'
    if 'folk' in n or 'folclor' in n or 'andin' in n or 'cueca' in n or 'trova' in n:
        return 'Folk / Folclor'
    if 'cumbia' in n or 'salsa' in n or 'tropical' in n:
        return 'Latino tropical'
    if 'jazz' in n:
        return 'Jazz'
    return 'Otros'

In [39]:
lolla_generos_limpio["categoria"] = lolla_generos_limpio["genero"].apply(categoria)

destacados = ["Rock", "Electrónica", "Pop"]
lolla_generos_limpio["destacado"] = lolla_generos_limpio["categoria"].apply(
    lambda x: x if x in destacados else "Otros"
)

tabla_destacada = lolla_generos_limpio.groupby(["edicion lolla ", "destacado"]).size().reset_index(name="cantidad")
tabla_destacada

    edicion lolla     destacado  cantidad
0             2011  Electrónica        19
1             2011        Otros        56
2             2011          Pop        12
3             2011         Rock        44
4             2012  Electrónica        24
5             2012        Otros        41
6             2012          Pop        11
7             2012         Rock        46
8             2013  Electrónica        23
9             2013        Otros        40
10            2013          Pop        24
11            2013         Rock        62
12            2014  Electrónica        29
13            2014        Otros        46
14            2014          Pop        24
15            2014         Rock        58
16            2015  Electrónica        32
17            2015        Otros        47
18            2015          Pop        16
19            2015         Rock        42
20            2016  Electrónica        23
21            2016        Otros        45
22            2016          Pop        28
23            2016         Rock        56
24            2017  Electrónica        34
25            2017        Otros        42
26            2017          Pop        33
27            2017         Rock        55
28            2018  Electrónica        64
29            2018        Otros        85
30            2018          Pop        38
31            2018         Rock        78
32            2019  Electrónica        98
33            2019        Otros       124
34            2019          Pop        40
35            2019         Rock        60
36            2022  Electrónica        21
37            2022        Otros       108
38            2022          Pop        36
39            2022         Rock        33
40            2023  Electrónica        41
41            2023        Otros        82
42            2023          Pop        46
43            2023         Rock        64
44            2024  Electrónica        29
45            2024        Otros       101
46            2024          Pop        38
47            2024         Rock        64
48            2025  Electrónica        27
49            2025        Otros        83
50            2025          Pop        45
51            2025         Rock        52
52            2026  Electrónica        38
53            2026        Otros        74
54            2026          Pop        62
55            2026         Rock        64

In [46]:
alt.renderers.enable('mimetype')

RendererRegistry.enable('mimetype')

In [47]:
grafico_destacado = alt.Chart(tabla_destacada).mark_bar().encode(
    y="edicion lolla :O",
    x=alt.X("cantidad:Q", stack="normalize", axis=alt.Axis(format="%")),
    color=alt.Color("destacado:N", scale=alt.Scale(
        domain=["Rock", "Electrónica", "Pop", "Otros"],
        range=["#e63946", "#457b9d", "#f4a261", "#cccccc"]
    )),
    tooltip=["edicion lolla ", "destacado", "cantidad"]
).properties(
    title="Géneros predominantes por edición: Rock, Electrónica y Pop"
)

grafico_destacado

<VegaLite 5 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/display_frontends.html#troubleshooting

In [48]:
grafico_destacado.save("vis_03.html")

from google.colab import files
files.download("vis_03.html")