### **1. Abrir la base**

In [28]:
import pandas as pd
import altair as alt

# Cargar archivo CSV
lolla = pd.read_csv(r"/content/Base de datos Lollapalooza 1(Base de datos 1).csv", delimiter=",", encoding="utf-8", dtype= {"edicion": int})
lolla.head()

,edicion lolla,artista,genero musical 01,genero musical 02,genero musical 03,integrantes,nacionalidad,headliner,escenario,veces en lollapalooza
0,2011,The Killers,Rock alternativo,Post-punk revival,New wave,4.0,Estadounidense,Sí,Coca Cola Zero Stage,1.0
1,2011,Jane's Addiction,Rock,Hard Rock,Punk Rock,4.0,Estadounidense,Sí,Claro Stage,1.0
2,2011,Kanye West,Hip Hop,Rap,Pop,1.0,Estadounidense,Sí,Coca Cola Zero Stage,1.0
3,2011,Cypress Hill,Rap,Hip Hop,Rap Rock,4.0,Estadounidense,No,Claro Stage,1.0
4,2011,30 Secons To Mars,Rock,Rock alternativo,Metal progresivo,4.0,Estadounidense,No,Coca Cola Zero Stage,1.0

### **2. Tamaño y estructura de la base**

In [29]:
lolla.shape

(1053, 10)

In [30]:
lolla.columns

Index(['edicion lolla ', 'artista ', 'genero musical 01', 'genero musical 02',
       'genero musical 03', 'integrantes', 'nacionalidad', 'headliner',
       'escenario', 'veces en lollapalooza'],
      dtype='object')

In [31]:
lolla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1053 entries, 0 to 1052
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   edicion lolla          1053 non-null   int64
 1   artista                1053 non-null   object
 2   genero musical 01      1051 non-null   object
 3   genero musical 02      959 non-null    object
 4   genero musical 03      697 non-null    object
 5   integrantes            1040 non-null   float64
 6   nacionalidad           1053 non-null   object
 7   headliner              1053 non-null   object
 8   escenario              1053 non-null   object
 9   veces en lollapalooza  1052 non-null   float64
dtypes: float64(2), int64(1), object(7)
memory usage: 82.4+ KB

### **3. Columnas individuales**

In [32]:
lolla["edicion lolla "].head()

0    2011
1    2011
2    2011
3    2011
4    2011
Name: edicion lolla , dtype: int64

In [33]:
lolla["genero musical 01"].head()

0    Rock alternativo
1                Rock
2             Hip Hop
3                Rap
4                Rock
Name: genero musical 01, dtype: object

In [34]:
lolla["genero musical 02"].head()

0    Post-punk revival
1            Hard Rock
2                  Rap
3              Hip Hop
4     Rock alternativo
Name: genero musical 02, dtype: object

In [35]:
lolla["genero musical 03"].head()

0            New wave
1           Punk Rock
2                 Pop
3            Rap Rock
4    Metal progresivo
Name: genero musical 03, dtype: object

### **4. Contar categorías**

In [36]:
lolla["edicion lolla "].value_counts()

edicion lolla
2019    125
2018    100
2022     93
2024     91
2023     90
2026     90
2025     74
2015     65
2017     61
2014     59
2016     57
2013     54
2011     50
2012     44
Name: count, dtype: int64

In [37]:
lolla["genero musical 01"].value_counts()

genero musical 01
Electrónica         95
Rock alternativo    73
Pop                 72
Rock                65
Hip hop             44
                    ..
Hyperpop             1
Trap Latino          1
Hardcore             1
Pop melancólico      1
Synth-pop            1
Name: count, Length: 204, dtype: int64

In [38]:
lolla["genero musical 02"].value_counts()

genero musical 02
Electrónica         44
Pop                 41
Indie pop           40
R&B                 32
Rock alternativo    30
                    ..
Cumbia pop           1
Pachanga             1
Dreampop             1
Pop                  1
Música andina        1
Name: count, Length: 227, dtype: int64

In [39]:
lolla["genero musical 03"].value_counts()

genero musical 03
Electrónica          27
Rock alternativo     24
R&B                  23
Indie pop            21
House                19
                     ..
Indie                 1
Drum and Bass         1
Rumba                 1
Cumbias               1
Música folclórica     1
Name: count, Length: 195, dtype: int64

### **5. Ordenar datos**

In [40]:
lolla_generos = lolla.melt(
    id_vars=["edicion lolla "],
    value_vars=["genero musical 01", "genero musical 02", "genero musical 03"],
    value_name="genero"
).dropna()

lolla_generos

      edicion lolla            variable             genero
0               2011  genero musical 01   Rock alternativo
1               2011  genero musical 01               Rock
2               2011  genero musical 01            Hip Hop
3               2011  genero musical 01               Rap
4               2011  genero musical 01               Rock
...              ...                ...                ...
3152            2026  genero musical 03               Rock
3154            2026  genero musical 03            Hip hop
3156            2026  genero musical 03          Post-punk
3157            2026  genero musical 03            Cumbias
3158            2026  genero musical 03  Música folclórica

[2707 rows x 3 columns]

In [41]:
lolla_generos = lolla_generos.drop(columns=["variable"])
lolla_generos

      edicion lolla              genero
0               2011   Rock alternativo
1               2011               Rock
2               2011            Hip Hop
3               2011               Rap
4               2011               Rock
...              ...                ...
3152            2026               Rock
3154            2026            Hip hop
3156            2026          Post-punk
3157            2026            Cumbias
3158            2026  Música folclórica

[2707 rows x 2 columns]

In [42]:
tabla_generos = lolla_generos.groupby(["edicion lolla ", "genero"]).size(). reset_index(name="cantidad")
tabla_generos

      edicion lolla         genero  cantidad
0               2011   Alternativo         2
1               2011         Blues         1
2               2011    Blues Rock         1
3               2011       Britpop         1
4               2011   Chamber pop         1
...              ...           ...       ...
1164            2026         Trap          1
1165            2026   Trap Latino         1
1166            2026  Tribal house         1
1167            2026         Trova         1
1168            2026        Urbano         3

[1169 rows x 3 columns]

In [43]:
top_generos = tabla_generos.groupby("genero")["cantidad"].sum().nlargest(10).index
tabla_top = tabla_generos[tabla_generos["genero"].isin(top_generos)]
tabla_top

      edicion lolla             genero  cantidad
14              2011       Electrónica         9
28              2011           Hip hop         2
35              2011         Indie pop         1
42              2011               Pop         2
44              2011          Pop rock         2
...              ...               ...       ...
1116            2026               Pop        10
1126            2026          Pop rock         6
1138            2026               R&B         5
1147            2026              Rock         5
1149            2026  Rock alternativo        15

[130 rows x 3 columns]

### 6. **Gráfico con Altair**

In [44]:
grafico = alt.Chart(tabla_top).mark_bar().encode(
    x="edicion lolla :O",
    y="cantidad:Q",
    color="genero:N",
    tooltip=["edicion lolla ", "genero", "cantidad"]
).properties(
    title="Diversificación de géneros musicales por edición"
)

grafico

alt.Chart(...)